export const clients = [
  {
    id: 1001,
    name: 'Maria Anders',
    country: { name: 'Germany', code: 'de' },
    company: 'Alfreds Futterkiste',
    date: '2016-04-22',
    status: 'qualified',
    verified: false,
    activity: 12,
    representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
    balance: 48200
  },
  {
    id: 1002,
    name: 'Francisco Chang',
    country: { name: 'Mexico', code: 'mx' },
    company: 'Centro comercial Moctezuma',
    date: '2017-11-05',
    status: 'new',
    verified: true,
    activity: 8,
    representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
    balance: 31500
  },
  {
    id: 1003,
    name: 'Roland Mendel',
    country: { name: 'Austria', code: 'at' },
    company: 'Ernst Handel',
    date: '2018-02-14',
    status: 'negotiation',
    verified: false,
    activity: 21,
    representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
    balance: 75900
  },
  {
    id: 1004,
    name: 'Helen Bennett',
    country: { name: 'UK', code: 'gb' },
    company: 'Island Trading',
    date: '2019-07-30',
    status: 'renewal',
    verified: true,
    activity: 5,
    representative: { name: 'Stephen Shaw', image: 'stephenshaw.png' },
    balance: 19800
  },
  {
    id: 1005,
    name: 'Yoshi Tannamuri',
    country: { name: 'Japan', code: 'jp' },
    company: 'Laughing Bacchus Winecellars',
    date: '2020-12-03',
    status: 'unqualified',
    verified: false,
    activity: 33,
    representative: { name: 'Ivan Magalhaes', image: 'ivanmagalhaes.png' },
    balance: 84200
  }
];

export const products = {
  "current_page": 1,
  "data": [
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "PARARRAYOS CON DISPOSITIVO DE CEBADO (PDC), RADIO DE PROTECCIÓN 63M, TIPO PDC NIVEL DE PROTECCION I SEGUN EE.TT. - INGESCO",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241666,
      "cantidad": 1,
      "precio": 5750,
      "detalle": "CON DISPOSITIVO DE CEBADO (PDC), RADIO DE PROTECCIÓN 63M, TIPO PDC NIVEL DE PROTECCION I SEGUN EE.TT. - INGESCO",
      "saldo": 0,
      "total_internado": 1,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 34453,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    },
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "MASTIL  DE Fº.Gº. Ø2'' x 6m SEGUN EE.TT. - F°G",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241667,
      "cantidad": 1,
      "precio": 700,
      "detalle": "DE Fº.Gº. Ø2'' x 6m SEGUN EE.TT. - F°G",
      "saldo": 0,
      "total_internado": 1,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 67246,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    },
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "ABRAZADERA DE ACERO DE Ø 2'' PARA MASTIL DE PARARRAYOS (Incl. Accesorios) SEGUN EE.TT. - F°G",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241668,
      "cantidad": 2,
      "precio": 38,
      "detalle": "DE ACERO DE Ø 2'' PARA MASTIL DE PARARRAYOS (Incl. Accesorios) SEGUN EE.TT. - F°G",
      "saldo": 0,
      "total_internado": 2,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 28049,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    },
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "ABRAZADERA METALICA 1 1/2'' CON 2 OREJAS, e=2mm SEGUN EE.TT. - F°G",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241669,
      "cantidad": 4,
      "precio": 4.5,
      "detalle": "METALICA 1 1/2'' CON 2 OREJAS, e=2mm SEGUN EE.TT. - F°G",
      "saldo": 0,
      "total_internado": 4,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 28049,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    },
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "TUBERIA PVC-SAP (ELECTRICA) DE 40MM DIAMETRO, 3M SEGUN EE.TT. - PLASTISUR",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241670,
      "cantidad": 101,
      "precio": 18,
      "detalle": "PVC-SAP (ELECTRICA) DE 40MM DIAMETRO, 3M SEGUN EE.TT. - PLASTISUR",
      "saldo": 0,
      "total_internado": 101,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 28401,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    },
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "AISLADOR PARA BAJADA DE CABLE DESNUDO DE PARARRAYOS (INCLUYE ACCESORIOS) SEGUN EE.TT. - F°G",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241671,
      "cantidad": 7,
      "precio": 20,
      "detalle": "PARA BAJADA DE CABLE DESNUDO DE PARARRAYOS (INCLUYE ACCESORIOS) SEGUN EE.TT. - F°G",
      "saldo": 0,
      "total_internado": 7,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 28779,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    },
    {
      "anio": "2025",
      "numero": "01611",
      "fecha": "2025-04-11",
      "siaf": "004840",
      "detalles_orden": "ORDEN DE COMPRA QUE SE GENERA POR ADQUISICIÓN DE MATERIALES PARA INSTALACION DE PARARRAYOS, SEGÚN ESPECIFICACIONES TÉCNICAS DEL REQUERIMIENTO N°3424 \n\nPENALIDAD\nEN CASO DE RETRASO POR INCUMPLIMIENTO DE LA ENTREGA DEL BIEN DENTRO DEL PLAZO ESTABLECIDO, LA ENTIDAD LE APLICARÁ AUTOMÁTICAMENTE UNA PENALIDAD POR MORA POR CADA DÍA DE RETRASO. SEGÚN LA DIRECTIVA REGIONAL N° 04-2016-GR PUNO, APROBADA CON RESOLUCIÓN ADMINISTRATIVA REGIONAL N° 031-2016-ORA-GR PUNO.\n\nSE ADJUNTA:\nESPECIFICACIONES TÉCNICAS\nACTA DE INDAGACIÓN DE MERCADO Y ACEPTACIÓN DE PRECIOS  \nMEMORANDO DIGITAL N°2107 - 2025-GR-PUNO/ORA-OASA\nCERTIFICACION DE CREDITO PRESUPUESTARIO 000003726.",
      "fecha_aceptacion": "2025-04-15",
      "plazo_internamiento": 3,
      "idprocedim": "07",
      "desprocedim": "MENOR A 8 UIT",
      "prod_proy": "2590087",
      "cod_meta": "0237",
      "desmeta": "MEJORAMIENTO DEL SERVICIO DE EDUCACIÓN SECUNDARIA EN I.E. JOSE MARIA ARGUEDAS DISTRITO DE LLALLI DE LA PROVINCIA DE MELGAR DEL DEPARTAMENTO DE PUNO",
      "desrubro": "CANON, S.CANON, REGALIAS, RENTA AD. Y PART.",
      "desuoper": "COSTO DIRECTO",
      "item": "POSTE DE C.A.C.  DE 12/300/180/360 M. INCLUYE PERILLA SEGUN EE.TT. - POSTES ALTIPLANO",
      "desmedida": "UNIDAD",
      "ruc": "20605774394",
      "rsocial": "COFELECT SOCIEDAD ANONIMA CERRADA",
      "telefono1": "950428882",
      "telefono2": "",
      "email": "cofelect.sac@gmail.com",
      "idcompradet": 241672,
      "cantidad": 1,
      "precio": 2690,
      "detalle": "DE 12/300/180/360 M. INCLUYE PERILLA SEGUN EE.TT. - POSTES ALTIPLANO",
      "saldo": 0,
      "total_internado": 1,
      "idcompra": 44300,
      "internado": "I",
      "iduoper": "00106",
      "idmeta": "1037",
      "idclasifica": "2.6.2.2.2.4",
      "codplan": "1501070203",
      "estado": null,
      "codigo": null,
      "idmedida": "024",
      "idcatalog": 67279,
      "saldo_conformidad": 0,
      "total_conformidad": 0
    }
  ],
  "first_page_url": "http://siluciav2-api.regionpuno.gob.pe/api/ordencompradetallado?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://siluciav2-api.regionpuno.gob.pe/api/ordencompradetallado?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    },
    {
      "url": "http://siluciav2-api.regionpuno.gob.pe/api/ordencompradetallado?page=1",
      "label": "1",
      "active": true
    },
    {
      "url": null,
      "label": "Next &raquo;",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://siluciav2-api.regionpuno.gob.pe/api/ordencompradetallado",
  "per_page": 20,
  "prev_page_url": null,
  "to": 7,
  "total": 7,
  "enums": []
}
// export default clients;